all : abc arg ArrayFlow2DieLoop big-little bug err foobar hello hi initial l negation order pi point ptrace show struct typedef u

clean :
	rm -rf abc arg ArrayFlow2DieLoop big-little bug err foobar hello hi initial l negation order pi point ptrace show struct typedef u *.o
