CFLAGS=-g -Wall
CC=gcc

OBJECT = blockread nonblockread nonblockread_timeout nonblockread_stdin\
	fcntldemo ioctldemo mmapdemo dirall dupdemo

ALL: $(OBJECT)

clean:
	rm -rf $(OBJECT) temp.foo hello somefile
