SHELL=/bin/sh

SUBDIRS=calc csapp env file funcpoint funcparam hello hellogcc hou io libc mem \
	msg pscan so TCPUDP test thread Car time TCPIP process coredumpdemo\
	signal bit syscall winsize ncursesdemo random getuid

include ../make/Make-subdir-targets
