ALL : Math.dll TestMath LoadDll

Math.dll : Math.c
	cl /LDd Math.c
TestMath.obj : TestMath.c
	cl /c TestMath.c
TestMath : TestMath.obj Math.lib
	link TestMath.obj Math.lib
LoadDll : LoadDll.c
	cl LoadDll.c
clean :
	rm -rf Math.dll Math.obj Math.lib Math.exp TestMath.obj TestMath.exe LoadDll.exe

