<?php
$txt1=trim($_POST['text1']);
$txt2=trim($_POST['text2']);
$txt3=trim($_POST['text3']);
$button=$_POST['button'];
?>
<!DOCTYPEHTMLPUBLIC"-//W3C//DTDHTML4.0Transitional//EN">
<html>
<head>
<title>迅雷和FlashGet,QQ旋风地址地址转换工具</title>
<metahttp-equiv="Content-Type"content="text/html;charset=gb2312">
<metacontent="迅雷,FlashGet,地址转换,"name="keywords">
</head>
<body>
<formname="form1"method="post"action="">
<hrsize="1">
<h3>迅雷转换</h3>
<P>转换地址：
<inputname="text1"value="<?phpecho$txt1;?>"type="text"style="width:516px;"/></P>
<P>转换后的：
<inputtype="text"value="<?php
if($button=="普通地址->迅雷地址")echo"thunder://".base64_encode("AA".$txt1."ZZ");
if($button=="迅雷地址->普通地址")echosubstr(base64_decode(str_ireplace("thunder://","",$txt1)),2,-2);
?>"style="width:516px;"/></P>
<P>
<inputtype="submit"name="button"value="普通地址->迅雷地址"/>
<inputtype="submit"name="button"value="迅雷地址->普通地址"/></P>
<h3>FlashGet转换</h3>
<P>FlashGet地址：
<inputname="text2"value="<?phpecho$txt2;?>"type="text"style="width:516px;"/></P>
<P>转换后地址：
<inputtype="text"value="<?php
if($button=="普通地址->FlashGet地址")echo"flashget://".base64_encode($txt2);
if($button=="FlashGet地址->普通地址")echostr_ireplace("[FLASHGET]","",base64_decode(str_ireplace("flashget://","",$txt2)));
?>"style="width:516px;"/></P>
<P>
<inputtype="submit"value="普通地址->FlashGet地址"name="button"/>
<inputtype="submit"value="FlashGet地址->普通地址"name="button"/></P>
<h3>QQ旋风转换</h3>
<P>QQ旋风地址：
<inputname="text3"value="<?phpecho$txt3;?>"type="text"style="width:516px;"/></P>
<P>转换后地址：
<inputtype="text"value="<?php
if($button=="普通地址->QQ旋风")echo"qqdl://".base64_encode($txt3);
if($button=="QQ旋风->普通地址")echobase64_decode(str_ireplace("qqdl://","",$txt3));
?>"style="width:516px;"/></P>
<P>
<inputtype="submit"value="普通地址->QQ旋风"name="button"/>
<inputtype="submit"value="QQ旋风->普通地址"name="button"/></P>
</form>
</body>
</html>
